- shell: which yum &>/dev/null && echo ok || echo no
  register: YUM_COMMAND
  tags:
  - system-base-init

- shell: which pacman &>/dev/null && echo ok || echo no
  register: PACMAN_COMMAND
  tags:
  - system-base-init

- shell: which apt-get &>/dev/null && echo ok || echo no
  register: APTGET_COMMAND
  tags:
  - system-base-init
  
- shell: ls /var/spool/cron/root &>/dev/null echo ok || echo no
  register: CRON_FILE
  tags:
    - CronFile

- shell: grep "pool.ntp.org" /var/spool/cron/root /etc/crontab &>/dev/null && echo ok || echo no
  register: CRON_STATUS
  tags:
    - CronStatus

- name: 更改时区 to any
  shell: ls /etc/localtime -lh |grep Shanghai &>/dev/null && echo ok || ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
  tags:
  - system-localtime

- name: 时间同步 Centos & RHEL & Fedora
  shell: rpm -qa |grep ntpdate &>/dev/null && echo ok || yum install ntpdate -y
  with_items: PACKAGES_FOR_CENTOS
  when:
  - '"ok" in YUM_COMMAND.stdout'
  tags:
  - system-base-init
  - RHEL-ntpd

- name: 时间同步 for Arch Linux
  shell: which openntpd &>/dev/null&& echo ok || pacman -S openntpd
  when:
  - '"ok" in PACMAN_COMMAND.stdout'
  tags:
  - arch-ntpd

- name: 时间同步 for Ubuntu
  shell: which ntpdate &>/dev/null && echo ok || apt-get install ntpdate -y
  when: 
  - '"ok" in APTGET_COMMAND.stdout'

- name: 创建定期执行文件/var/splool/cron/root
  shell: touch /var/spool/cron/root
  when: 
  - '"no" in CRON_FILE.stdout'

- name: 增加cron定期执行任务
  shell: echo "58 23 * * * root ntpdate cn.pool.ntp.org" >> /var/spool/cron/root
  when:
  - '"no" in CRON_STATUS.stdout'

- name: 禁用Selinux For RHEL
  shell: grep 'SELINUX=enforcing' /etc/selinux/config &> /dev/null && sed -i 's/SELINUX=enforcing/SELINUX=permissive/g' /etc/selinux/config && setenforce 0 || echo ok
  when:
  - '"ok" in YUM_COMMAND.stdout'
  tags:
  - system-base-init
  - RHEL-selinux
